### ISSUE TITLE
Make AA13 fire multiple pellets at once

### ISSUE THREAD

**Issue by Rainyan** [NeotokyoRevamp/neo#47]
Currently, the AA13 fires a single bullet/pellet. Supa7 and HL2MP shotty have similar multi-pellet code.

**Comment by brekiy** [comment]
Hi, if this project is still being worked on I'd like to take this issue.

**Comment by Rainyan** [comment]
Hey, help is greatly appreciated, thanks! I've assigned this issue to you.

**Comment by Rainyan** [comment]
Resolved by #56
