### ISSUE TITLE
Implement Supa7 slugs

### ISSUE THREAD

**Issue by Rainyan** [NeotokyoRevamp/neo#48]
The Supa7 should be able to load single-pellet slugs when using alt fire and there is room in the chamber for the slug.

**Comment by brekiy** [comment]
Hi, if this project is still being worked on I'd like to take this issue.

**Comment by Rainyan** [comment]
Hey, help is greatly appreciated, thanks! I've assigned this issue for you.

**Comment by Rainyan** [comment]
Resolved by #56
